name: googler
adopt-info: googler
summary: power tool to Google (Web & News) and Google Site Search from the command-line
description: |
  googler is a power tool to Google (Web & News) and Google Site
  Search from the command-line. It shows the title, URL and abstract
  for each result, which can be directly opened in a browser from the
  terminal. Results are fetched in pages (with page navigation).
  Supports sequential searches in a single googler instance.
  googler isn't affiliated to Google in any way.
base: core18
grade: stable
confinement: strict

apps:
  googler:
    command: usr/local/bin/googler
    plugs: [desktop, network, x11]
    environment:
      PYTHONIOENCODING: utf-8

parts:
  googler:
    plugin: make
    source: https://github.com/jarun/googler.git
    make-parameters:
      - disable-self-upgrade
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "${last_committed_tag#v}"
      else
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    stage-packages: [python3, xsel, xclip]
