name: googler
version: '3.3'
summary: power tool to Google (Web & News) and Google Site Search from the command-line
description: |
  googler is a power tool to Google (Web & News) and Google Site
  Search from the command-line. It shows the title, URL and abstract
  for each result, which can be directly opened in a browser from the
  terminal. Results are fetched in pages (with page navigation).
  Supports sequential searches in a single googler instance.
  googler isn't affiliated to Google in any way.

confinement: devmode

apps:
  googler:
    command: usr/local/bin/googler
    plugs: [network]
    environment:
      PYTHONIOENCODING: utf-8

parts:
  googler:
    plugin: make
    source: https://github.com/jarun/googler/archive/v3.3.tar.gz
    prepare: make disable-self-upgrade
    stage-packages: [python3]